django_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from django_app import views

app_name = 'django_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('data/', views.list_compr, name='list_comrp'),
    path('login_f/', views.login_f, name='login'),
    path('logout/', views.logout_f, name='logout'),

    path('posts/', views.post_list, name='post_list'),
    path('post/<int:pk>/detai/l', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('all_users/', views.all_users, name='all_users'),
    path('register/', views.register, name='register'),
    path('get_data_excel/', views.get_data_excel, name='get_data_excel'),
    # path('post/create', views.post_create, name='post_create'),
    # path('post/<int:pk>/detail/', views.post_detail, name='post_detail'),
    # path('post/<int:pk>/update/', views.post_update, name='post_update'),
    # path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),

]

django_settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_app.urls')),
]

django_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Post(models.Model):
    user = models.ForeignKey(
        editable=True,
        blank=True,
        null=True,
        default=None,
        verbose_name='Пользователь',
        help_text='<small class="text-muted">ForeignKey</small><hr><br>',
        to=User,
        on_delete=models.SET_NULL,
    )

    title = models.CharField(
        verbose_name="Заголовок",
        default="",
        editable=True,
        blank=True,
        unique=True,
        db_index=True,
        max_length=150
    )

    description = models.TextField(
        verbose_name="Описание",
        default="",
        editable=True,
        blank=True,

        max_length=300
    )

    class Meta:
        app_label = 'django_app'
        ordering = ('id',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return f"Post: {self.title} {self.description[:30]} [{self.id}]"

django_app/views.py
import json

from django.contrib.auth import get_user_model

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import update_last_login, User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, JsonResponse, HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from openpyxl.workbook import Workbook

from django_app import models

from django_app.models import Post


def list_compr(request: HttpRequest) -> JsonResponse:
    data = [
        {
            'id': x,
            'name': f'Emil {x}',
            'age': x
        }
        for x
        in range(1, 100)]

    with open('temp/logs.txt', 'w') as logs_file:
        json.dump(data, logs_file)

    return JsonResponse(data=data, safe=False)


def login_f(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        context = {}
        return render(request, 'login.html', context=context)
    if request.method == 'POST':
        username = request.POST.get('username', "")
        password = request.POST.get('password', "")
        if username and password:
            user_obj = authenticate(username=username, password=password)
            if user_obj:
                login(request, user_obj)
                update_last_login(sender=None, user=user_obj)
                return redirect(reverse('django_app:post_list', args=()))
            else:
                raise Exception('данные не совпадают')
        else:
            raise Exception('no data')


def logout_f(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse('django_app:login', args=()))


def post_list(request: HttpRequest) -> HttpResponse:
    posts = models.Post.objects.all()

    if request.method == 'POST':
        search_by_title = request.POST.get('search', None)
        if search_by_title is not None:
            posts = posts.filter(title__contains=str(search_by_title))
        filter_by_user = request.POST.get('filter', None)
        if filter_by_user is not None:
            posts = posts.filter(user=User.objects.get(username=filter_by_user))

    selected_page_number = request.GET.get('page', 1)
    selected_limit_objects_per_page = request.GET.get('limit', 6)

    page = CustomPaginator.paginate(
        object_list=posts, per_page=selected_limit_objects_per_page, page_number=selected_page_number
    )

    users = User.objects.all()
    context = {'page': page, 'username': request.user, 'users': users}
    return render(request, 'post_list.html', context=context)


def register(request: HttpRequest) -> HttpResponse:
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    if username and password:
        User.objects.create(
            username=username,
            password=make_password(password)
        )
        return redirect(reverse('django_app:login'))
    return render(request, 'register.html')


def home(request: HttpRequest) -> HttpResponse:
    context = {}
    return render(request, 'components/base.html', context=context)


def post_detail(request: HttpRequest, pk: int):
    post = models.Post.objects.get(id=pk)
    context = {'post': post}
    return render(request, 'post_detail.html', context=context)


def post_create(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        context = {}
        return render(request, 'post_create.html', context=context)
    elif request.method == 'POST':
        print('printed', request.POST)
        title = request.POST.get('title', None)
        description = request.POST.get('description', "")
        models.Post.objects.create(
            user=request.user,
            title=title,
            description=description,
        )

        context = {}
        return redirect(reverse('django_app:post_list', args=()))


def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
    models.Post.objects.get(id=pk).delete()
    return redirect(reverse('django_app:post_list', args=()))


def get_data_excel(request):
    user_workbook = Workbook()
    user_worksheet = user_workbook.active

    post_workbook = Workbook()
    post_worksheet = post_workbook.active

    users = User.objects.all()
    posts = Post.objects.all()

    for user_header_index, user_header_value in enumerate(['user_id', 'username', 'password', 'email', 'is_staff'], 1):
        user_worksheet.cell(1, user_header_index, user_header_value)
    for row_index, user in enumerate(users, 2):
        user_id = user.id
        username = user.username
        password = user.password
        email = user.email
        is_staff = user.is_staff
        cols = [user_id, username, password, email, is_staff]
        for col_index, value in enumerate(cols, 1):
            user_worksheet.cell(row_index, col_index, value)
    user_workbook.save('temp/users_data.xlsx')

    for post_header_index, post_header_value in enumerate(['post_user', 'title', 'description'], 1):
        post_worksheet.cell(1, post_header_index, post_header_value)
    for row_index_posts, post in enumerate(posts, 2):
        post_user = str(post.user)
        title = post.title
        description = post.description
        post_cols = [post_user, title, description]
        for col_index_posts, post_value in enumerate(post_cols, 1):
            post_worksheet.cell(row_index_posts, col_index_posts, post_value)
    post_workbook.save('temp/posts_data.xlsx')
    return HttpResponse('<h1>Данные успешно выгружены в файл!</h1>')


class CustomPaginator:
    @staticmethod
    def paginate(object_list: any, per_page=5, page_number=1):
        # https://docs.djangoproject.com/en/4.1/topics/pagination/
        paginator_instance = Paginator(object_list=object_list, per_page=per_page)
        try:
            page = paginator_instance.page(number=page_number)
        except PageNotAnInteger:
            page = paginator_instance.page(number=1)
        except EmptyPage:
            page = paginator_instance.page(number=paginator_instance.num_pages)
        return page


def all_users(request: HttpRequest) -> HttpResponse:
    user = get_user_model()
    users = user.objects.all()
    context = {'users': users}
    return render(request, 'all_users.html', context=context)

templates/all_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Это список всех пользователей сайта:</h1>
    <ol>
        {% for user in users %}
             <li>{{ user }}</li>
        {% endfor %}
    </ol>
</body>
</html>

templates/components/base.html
{% load static %}
{% block head %}
<html lang="en" class="h-100"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    {% block title %}
    <title>Homework website</title>
    {% endblock title %}


    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="{% static 'fontawesome/css/all.css' %}" rel="stylesheet" crossorigin="anonymous">




<link href="/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
{% endblock head %}


  <body class="d-flex h-100 text-center text-bg-dark">
{% block navbar %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto bg-light p-5">
    <div class="">
      <a href="{% url 'django_app:home' %}" class="float-md-start mb-0 text-decoration-none h5">Главная страница</a>
      <nav class="nav nav-masthead justify-content-around float-md-end">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="{% url 'django_app:all_users' %}">Список пользователей</a>
        <a class="nav-link fw-bold py-1 px-5" href="{% url 'django_app:register' %}">Регистрация</a>
        <a class="nav-link fw-bold py-1 px-0" href="{% url 'django_app:login' %}">Логин</a>
          <a class="nav-link fw-bold py-1 px-5" href="{% url 'django_app:get_data_excel' %}">Выгрузить все данные</a>

          <p class="nav-link fw-bold py-1 px-5 text text-danger" href="{% url 'django_app:login' %}">{{ username }}</p>

      </nav>
    </div>
  </header>
{% endblock navbar %}
{% block main %}

    {% comment %}
    Проверяю, как работают теги
    {% endcomment %}

{% filter force_escape|lower %}
    Этот текст находится в фильтре!!!
{% endfilter %}
    <br>
    <br>
    <br>
  <main class="px-3">
    <h1>Домашка с ToDo листами</h1>
    <p class="lead">Нажмите на кнопку ниже, что посмотреть ToDo листы</p>
    <p class="lead">
          <a href="{% url 'django_app:post_list' %}" class="btn btn-lg btn-light fw-bold border-white bg-white border border-5 border-dark">All Posts</a>
    </p>
  </main>

{% block footer %}
  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
{% endblock footer %}

</div>
</body></html>
{% endblock main %}

templates/components/paginator.html
<ul class="pagination pagination-lg justify-content-center">
    {% if page.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1" aria-disabled="true"><span aria-hidden="true">&laquo;</span></a>
        </li>
    {% endif %}

    {% if page.number != 1 %}
        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
    {% endif %}


    <li class="page-item disabled"><a class="page-link" href="#">{{ page.number }} страница из {{ page.paginator.num_pages }}</a></li>

    {% if page.paginator.num_pages > 1 %}
        <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>
    {% endif %}

    {% if page.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
        </li>
    {% endif %}

  </ul>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>

<section class="py-5 text-center container">
    <main class="form-signin">
  <form action="{% url 'django_app:login' %}"
    method="POST"
    enctype="multipart/form-data">
   <div class="text-end">
           {% if user.is_authenticated %}
                <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2">Выйти ({{ user.username }})</a>
            {% else %}
                <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Войти (аноним)</a>
            {% endif %}

      {% csrf_token %}
      <h1 class="h3 mb-3 fw-normal">Введите свои данные</h1>
    {{request.user}}
    <div class="form-floating">

      <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="username">
      <label for="floatingInput">Имя пользователя</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
      <label for="floatingPassword">Пароль</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
  </form>
</main>
</section>
</body>
</html>

templates/post_create.html
{% extends 'components/base.html' %}
{%  block main %}
    <div style="margin-bottom: 350px">
        <main class="form-signin w-75 m-auto">
            <form action="{% url 'django_app:post_create' %}"
                 method="POST"
                 enctype="multipart/form-data">
      {% csrf_token %}
                 <h1 class="h3 mb-3 fw-normal">Создайте свой пост!</h1>
                     <div class="form-floating">
                        <input type="text" class="form-control" id="floatingInput" placeholder="Заголовок" name="title">
                        <label for="floatingInput">Заголовок</label>
        </div>
                    <div class="form-floating">
                        <input type="text" class="form-control" id="floatingPassword" placeholder="Описание" name="description">
                        <label for="floatingPassword">Описание</label>
    </div>

    <button class="w-100 btn btn-lg btn-primary" type="submit">Опубликовать</button>
  </form>
</main>
    </div>
{%  endblock main %}

templates/post_detail.html
{% extends "components/base.html" %}
{% block main %}
<div class="col-lg-4 border border-3 border-dark p-5 mx-auto w-75" style="margin-left: 270px; margin-bottom: 300px">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        <h2 class="fw-normal">{{ post.title }}</h2>
        <p>{{ post.description }}</p>
            <a href="{% url 'django_app:post_delete' post.id %}" class="text-decoration-none btn">
             <i class="fa-solid fa-trash text-danger"></i>
         </a>
        <p><a class="btn btn-secondary" href="{% url 'django_app:post_list' %}">Назад</a></p>
      </div>
{% endblock main %}

templates/post_list.html
{% extends "components/base.html" %}
{% block main %}
     {% comment %}
    Проверяю, как работают теги
    {% endcomment %}
<form action="{% url 'django_app:post_list' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
        <div class="input-group m-3">
            <input type="search" class="form-control p-3 w-50"  placeholder="введите сюда часть названия..." name="search">
            <button class="btn btn-lg btn-primary" type="submit">искать</button>
        </div>
<select class="form-select form-select-lg mb-3" required aria-label=".form-select-lg example" name="filter">
  <option selected>Выберите пользователя для фильтрации</option>
    {% for i in users %}
        <option value="{{ i.username }}">{{ i.username }}</option>
    {% endfor %}
</select>
            <button class="btn btn-lg btn-primary" type="submit">искать</button>
  </form>

<a href="{% url 'django_app:post_create' %}" class="btn btn-primary btn-lg m-5 p-3">Создать пост</a>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for post in page %}
     <div class=" container container-fluid w-25 border border-danger m-5">
      <div class="col p-1">
        <h2 class="fw-normal">{{ post.title }}</h2>
        <p>{{ post.description }}</p>
        <p><a class="btn btn-secondary" href="{% url 'django_app:post_detail' post.id %}">Подробнее</a></p>
          <a href="{% url 'django_app:post_delete' post.id %}" class="text-decoration-none btn">
             <i class="fa-solid fa-trash text-danger"></i>
         </a>

        </div>
     </div>

    {% endfor %}
    </div>
    {% include 'components/paginator.html' %}
{% endblock main %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>

<section class="py-5 text-center container">
    <main class="form-signin">
  <form action="{% url 'django_app:register' %}"
    method="POST"
    enctype="multipart/form-data">
   <div class="text-end">

      {% csrf_token %}
      <h1 class="h3 mb-3 fw-normal">Регистрация аккаунта</h1>
    {{request.user}}
    <div class="form-floating">

      <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="username">
      <label for="floatingInput">Имя пользователя</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
      <label for="floatingPassword">Пароль</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
  </form>
</main>
</section>
</body>
</html>